function checkAddressValue(){if(!checkreceiverName()){alert("请正确填写姓名");return false;}
if(!checkreceiverAddress()){alert("请正确填写地址");return false;}
if(!checkreceiverPostCode()){alert("请正确填写邮编");return false;}
var phone=jQuery("#receiverTelephone").val();var mobile=jQuery("#receiverMobilePhone").val();if(phone==""&&mobile==""){jQuery("#receiverMobilePhone").focus();jQuery("#heckout_consignee_input7").html("<font color=red>请填写手机或者固定电话！</font>");alert("请填写手机或者固定电话");return false;}
if(mobile!=""){if(isNaN(mobile)){jQuery("#heckout_consignee_input7").html("<font color=red>手机号码应该为数字！</font>");alert("手机号码应该为数字！");return false;}else if(mobile.length!=11){jQuery("#heckout_consignee_input7").html("<font color=red>手机号应为11位 ！</font>");alert("手机号应为11位！");return;}
jQuery("#heckout_consignee_input7").html("");}
if(phone!=""){var patrn=/^((\d){2,4}[-]{0,1})?((\d){7,8})(-(\d{3,4}))?$/;if(!patrn.exec(phone)){jQuery("#heckout_consignee_input4").html("<font color=red>联系电话应为数字,如：020-12345678-5587</font>");alert("联系电话应为数字,如：020-12345678-5587");return false;}else{jQuery("#heckout_consignee_input4").html("");}}
var regionid=jQuery("#regionId").val();if(regionid==""||regionid==1602){jQuery("#heckout_consignee_input9").html("<font color=red>请选择您的所在省市！</font>");alert("请选择您的所在省市！");return false;}else if(!checkRegionId()){jQuery("#heckout_consignee_input9").html("<font color=red>请选择您的所在省市！</font>");alert("请选择您的所在省市！");return false;}
return true;}
function saveAddress(){if(checkAddressValue()){var shouhtml;var ratvalue="0";var rttvalue="0";var newEntry=new consignee();var newEntryto=new userTradeInfo();newEntry.name=jQuery("#receiverName").val();newEntryto.accepterName=newEntry.name;newEntry.address=jQuery("#receiverAddress").val();newEntryto.accepterAddress=newEntry.address;newEntry.telephone=jQuery("#receiverTelephone").val();newEntryto.telephone=newEntry.telephone;newEntry.mobilephone=jQuery("#receiverMobilePhone").val();newEntryto.mobilephone=newEntry.mobilephone;var postCodeTemp=jQuery("#receiverPostCode").val();if(postCodeTemp==''||postCodeTemp==null){postCodeTemp='000000';}
newEntry.postalcode=postCodeTemp;newEntryto.postalCode=newEntry.postalcode;newEntry.addressType=ratvalue;newEntry.telephoneType=rttvalue;newEntry.regionId=jQuery("#regionId").val();newEntryto.regionId=newEntry.regionId;newEntryto.userId=userid;if(jQuery.trim(jQuery("#addressid").val())==""){var newEntryStr=JSON.stringify(newEntry);jQuery.post(frontPath+"/Cart/addAddressReturnIdForjQuery.do?T="+ Math.random(),{newEntryStr:newEntryStr},function(data){var consigneeIDs=jQuery.trim(data);if(parseInt(consigneeIDs)){newEntryto.consigneeId=parseInt(consigneeIDs);jQuery("#addressid").val(consigneeIDs);closeAddDiv('orders_infom1','orders_boxm1');var newEntrytoStr=JSON.stringify(newEntryto)
jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});chageAddress(newEntry.name,newEntry.regionId,newEntry.address,newEntry.postalcode,newEntry.mobilephone,newEntry.telephone);}});}else{newEntry.id=jQuery("#addressid").val();var newEntryStr=JSON.stringify(newEntry);jQuery.post(frontPath+"/Cart/updateAddressEntryForjQuery.do?T="+Math.random(),{newEntryStr:newEntryStr},closeAddDiv('orders_infom1','orders_boxm1'));var newEntrytoStr=JSON.stringify(newEntryto);jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});chageAddress(newEntry.name,newEntry.regionId,newEntry.address,newEntry.postalcode,newEntry.mobilephone,newEntry.telephone);}
showaddressdiv('orders_boxm2','orders_infom2');}}
function changeShouHuoRegion(){var theAdr="";for(var i=1;i<jQuery(".selectTree").length;i++){var obj=document.getElementById("region_"+i);theAdr+=" "+obj.options[obj.selectedIndex].text;}
jQuery("#shouhuoRegion").html("地区："+theAdr);}
function chageAddress(shouhuoName,shouhuoRegion,shouhuoAddress,shouhuoPCode,shouhuoMP,shouhuoTL){jQuery("#shouhuoName").html("姓名："+shouhuoName);changeShouHuoRegion();jQuery("#shouhuoAddress").html("详细地址："+shouhuoAddress);if(shouhuoPCode='000000'){shouhuoPCode='';}
jQuery("#shouhuoPCode").html("邮编："+shouhuoPCode);jQuery("#shouhuoMP").html("手机："+shouhuoMP);jQuery("#shouhuoTL").html("固定电话："+shouhuoTL);}
function checkreceiverName(){var $receiverName=jQuery("#receiverName");var $input1=jQuery("#heckout_consignee_input1")
if($receiverName.val()==""){$input1.html("<font color=red>请填写收货人姓名!</font>");return false;}else{$input1.html("");return true;}}
function checkreceiverAddress(){var $receiverAddress=jQuery("#receiverAddress");var $input6=jQuery("#heckout_consignee_input6");if($receiverAddress.val()==""){$input6.html("<font color=red>请填写详细地址！</font>");return false;}else{return true;}}
function checkreceiverPostCode(){var $receiverPostCode=jQuery("#receiverPostCode");var $input3=jQuery("#heckout_consignee_input3");if($receiverPostCode.val()==""){return true;}else{if($receiverPostCode.val().length!=6||isNaN($receiverPostCode.val())){$input3.html("<font color=red>请填写正确的邮编！</font>");return false;}else{$input3.html("");return true;}}}
function checkreceiverTelephone(){var $receiverTelephone=jQuery("#receiverTelephone");var $input4=jQuery("#heckout_consignee_input4");var $receiverMobilePhone=jQuery("#receiverMobilePhone");var $input7=jQuery("#heckout_consignee_input7");if($receiverTelephone.val()==""&&$receiverMobilePhone.val()==""){$input7.html("<font color=red>请填写手机或者固定电话！</font>");}else{var telephoe=$receiverTelephone.val();var mobiephone=$receiverMobilePhone.val();var patrn=/^((\d){2,4}[-]{0,1})?((\d){7,8})(-(\d{3,4}))?$/;if(telephoe!=""){if(!patrn.exec(telephoe)){$input4.html("<font color=red>联系电话应为数字,如：020-12345678-8188!</font>");return;}else{$input4.html("");$input7.html("");}}
if(mobiephone!=""){if(isNaN(mobiephone)){$input7.html("<font color=red>手机号应为数字 ！</font>");return;}else if(mobiephone.length!=11){$input7.html("<font color=red>手机号应为11位 ！</font>");return;}
$input7.html("");$input4.html("");}else{$input7.html("");$input4.html("");}}}
function checkreceiverEmail(){return true;}
function checkAddress(){var checka=true;if(jQuery("#receiverName").val()==""){checka=false;}else{jQuery("#heckout_consignee_input1").html("");}
if(jQuery("#receiverAddress").val()==""){checka=false;}else{}
jQuery("#heckout_consignee_input3").html("");if(jQuery("#receiverEmail").val()==""){checka=false;}else{jQuery("#heckout_consignee_input10").html("");}
if(jQuery("#receiverTelephone").val()==""&&jQuery("#receiverMobilePhone").val()==""){checka=false;}else{var patrn=/^((\d){2,4}[-]{0,1})?((\d){7,8})(-(\d{3,4}))?$/;var telephoe=jQuery("#receiverTelephone").val();var mobilephone=jQuery("#receiverMobilePhone").val();if(telephoe!=""){if(!patrn.exec(telephoe)){jQuery("#heckout_consignee_input4").html("<font color=red>联系电话应为数字,如：020-12345678 或者12345678 !</font>");checka=false;}else{jQuery("#heckout_consignee_input4").html("");}}
if(mobilephone!=""){if(isNaN(mobilephone)){jQuery("#heckout_consignee_input7").html("<font color=red>手机号应为数字 ！</font>");checka=false;}else{jQuery("#heckout_consignee_input7").html("");}}}}
function checkRegionId(){var isAllSelect=true;jQuery(".selectTree").each(function(){if(this.selectedIndex==0){isAllSelect=false;}});return isAllSelect;}
function isEmail(email){if(email.length>50){return false;}
var re=/^(([0-9a-zA-Z]+)|([0-9a-zA-Z]+[_.0-9a-zA-Z-]*[0-9a-zA-Z]+))@([a-zA-Z0-9-]+[.])+([a-zA-Z]{2}|net|NET|com|COM|gov|GOV|mil|MIL|org|ORG|edu|EDU|int|INT)$/;if(email.search(re)!=-1){return true;}
return false;}
function closeAddDiv(div1,div2){jQuery("#"+div1).hide();jQuery("#"+div2).show();}
function closePickupMode(div1,div2){jQuery("#"+div1).hide();jQuery("#"+div2).show();jQuery("#order_detailCon").show();jQuery("#orderJs").show();jQuery("#order_sub").show();}
function closeAddTheReceiverDiv(div1,div2){closeAddDiv(div1,div2);changeShouHuoRegion();}
function showaddressdiv(div1,div2){jQuery("#"+div1).hide();jQuery("#"+div2).show();}
function showConsolidationOrder(div1,div2){jQuery.post("/Cart/ConsolidationOrderList.do",function(data){jQuery("#orders_boxm9").html(data);});closeAddDiv(div1,div2);}
function controlTheConsolidationOrder(){jQuery("#consolidationOrderDiv").show();jQuery.post("/Cart/ConsolidationOrder.do",function(data){jQuery("#consolidationOrderDiv").html(data);});}
function refreshRegion(id){SelectTree.setValue(id,jQuery('#'+id).val());}
function GetRadioValue(RadioName){var obj;obj=document.getElementsByName(RadioName);if(obj!=null){var i;for(i=0;i<obj.length;i++){if(obj[i].checked){return obj[i].value;}}}
return null;}
function savaPaymode(){var newEntryto2=new userTradeInfo();if(GetRadioValue("p2mid")==null){alert("请选择支付方式");return;}
newEntryto2.deliveryModeId=GetRadioValue("DeliveryMode");newEntryto2.payModeId=GetRadioValue("p2mid");newEntryto2.userId=userid;var newEntrytoStr=JSON.stringify(newEntryto2);jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});setTimeout("controlTheConsolidationOrder()",100);var paymode=jQuery("#paymode_"+newEntryto2.payModeId).html();jQuery("#payinfo").html(paymode);showaddressdiv("orders_infom3","orders_boxm3");showaddressdiv('orders_boxm8','orders_infom8');}
function savaPickupMode(){if(!radiocheck("thePickupMode")){alert("请选择缺货处理！");showaddressdiv('orders_boxm8','orders_infom8');return;}else{var newEntryto2=new userTradeInfo();newEntryto2.userId=userid;newEntryto2.pickupMode=jQuery("#pickupMode").val();var newEntrytoStr=JSON.stringify(newEntryto2);jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});closePickupMode('orders_infom8','orders_boxm8');}}
function vCodeRefresh1(id){jQuery("#"+id).attr("src",frontPath+"/ValidateCode?dumy="+ Math.random());}
function vCodeRefresh(id){jQuery("#"+id).attr("src",frontPath+"/ValidateCode?dumy="+ Math.random());}
function checkform(){if(jQuery("#receiverName").val()==""){alert("请您输入收货人姓名！");return false;}
var regionid=jQuery("#regionId").val();if(regionid==""||regionid==1602){alert("请选择您的所在省市！");return false;}
if(jQuery("#receiverAddress").val()==""){alert("请您输入详细地址！");return false;}
var post=jQuery("#receiverPostCode").val()
if(post==""||isNaN(post)){post='000000';}
if(post.length!=6){alert("收货人邮编必须是6位数字！");return false;}
if(jQuery("#receiverTelephone").val()==""&&jQuery("#receiverMobilePhone").val()==""){alert("收货人固定电话和手机号码必须填写一个！");return false;}
if(jQuery("#receiverTelephone").val()!=""){var patrn=/^((\d){2,4}[-]{0,1})?((\d){7,8})(-(\d{3,4}))?$/;if(!patrn.exec(jQuery("#receiverTelephone").val())){alert("联系电话应为数字,如：010-62303100-8188 或者 62303100-8188!");return false;}}
if(jQuery("#receiverMobilePhone").val()!=""){if(isNaN(jQuery("#receiverMobilePhone").val())){alert("手机号码应该为数字！");return false;}}
if(!checkreceiverEmail()){alert("请输入您的电子邮件");return false;}
if(!issVirtualCard){var dmoderadio=document.getElementsByName("DeliveryMode");var dmoderadiolen=dmoderadio.length;if(dmoderadiolen<1){alert("商家尚未配置配送方式，不能够继续购物！");showaddressdiv('orders_boxm2','orders_infom2');return false;}else{var dmodesel=false;dmodesel=radiocheck("DeliveryMode");if(dmodesel==false){alert("请选择配送方式！");showaddressdiv('orders_boxm2','orders_infom2');return false;}}}
var peisongtime=GetRadioValue("delivergoodtime");if(jQuery("#thePeiSongTime").val()==1){if(peisongtime==null){alert("请选择配送时间");showaddressdiv('orders_boxm2','orders_infom2');return false;}}
var payradio=document.getElementsByName("p2mid");var payradiolen=payradio.length;if(payradiolen<1){alert("商家尚未配置支付方式，不能够继续购物！");showaddressdiv('orders_boxm3','orders_infom3');return false;}else{var paymodesel=false;paymodesel=radiocheck("p2mid");if(paymodesel==false){alert("请选择支付方式！");showaddressdiv('orders_boxm3','orders_infom3');return false;}}
if(radiocheck("invoiceTitle")){var invoiceTitleObj=document.getElementsByName("invoiceTitle");var invoiceTitleValue;for(var j=0;j<invoiceTitleObj.length;j++){if(invoiceTitleObj[j].checked){invoiceTitleValue=invoiceTitleObj[j].value;}}
var $personName=jQuery("#personName");if($personName.val()==null||jQuery.trim($personName.val())==''){alert("请填写发票抬头！");return false;}else{jQuery("#companyName").val(jQuery("#personName").val());}
var perInvoiceContentElement=document.getElementById("perInvoiceContent1");var perInvoiceContent=perInvoiceContentElement.options[perInvoiceContentElement.selectedIndex].value;if("请选择"==perInvoiceContent){alert("请选择发票内容！");return false;}else{jQuery("#invoiceContent").val(perInvoiceContent);}}
if(!radiocheck("thePickupMode")){alert("请选择缺货处理！");showaddressdiv('orders_boxm8','orders_infom8');return false;}else{var thePickupModeObj=document.getElementsByName("thePickupMode");var thePickupModeValue;for(var j=0;j<thePickupModeObj.length;j++){if(thePickupModeObj[j].checked){thePickupModeValue=thePickupModeObj[j].value;}}
jQuery("#pickupMode").val(thePickupModeValue);}
if(jQuery("#cartValidate").val()==null||jQuery("#cartValidate").val()==""){alert("验证码不能为空");jQuery("#cartValidate").focus();return false;}
jQuery("#submitButtonA").hide();jQuery("#submitButtonAA").show();checkval2();return true;}
function checkval2(){jQuery.post(frontPath+"/Cart/checkValidateForjQuery.do?T="+Math.random(),checkval);}
function checkval(data){if(jQuery.trim(data)==jQuery("#cartValidate").val()){document.getElementById("PayForm").submit();}else{alert("验证码错误！");vCodeRefresh('ValidateCode_1');jQuery("#submitButtonA").show();jQuery("#submitButtonAA").hide();}}
var show1=true;var show2=true;var show3=true;function onchangeCardAndCoupon(id){if(id=='onJustCoupon'){var virtualCardPriceForCheck=jQuery("#virtualCardPrice").html();if(jQuery("#CouponNumSwitch").val()>0){jQuery("#gouwuCard").html("<ul class='coupons'><li><span class='red'>温馨提示：GG券和羊展券不能同时使用</span></li></ul>");}else if(virtualCardPriceForCheck!=''&&virtualCardPriceForCheck!='0.00'){jQuery("#gouwuCard").html("<ul class='coupons'><li><span class='red'>温馨提示：GG券和满减券不能同时使用</span></li></ul>");}
else{if(show1){var timetemp=(new Date()).valueOf();jQuery("#gouwuCard").load(frontPath+"/Card/gouWuCard.do?t="+timetemp);jQuery("#fullcutCard").css('display','none');}else
{jQuery("#fullcutCard").css('display','none');jQuery("#gouwuCard").css('display','block');}}
jQuery("#gouwuCard").css('display','block');jQuery("#order_ticket").attr("class","order_ticket order_ticketBg");jQuery("#JustCoupon").show();jQuery("#theCouponClose").hide();jQuery("#theCouponOpen").show();}
if(id=='onJustCouponpostfree'){if(show3){var timetemp=(new Date()).valueOf();jQuery("#postfreeCard").load(frontPath+"/Card/postfreeCard.do?t="+timetemp);}else
{jQuery("#postfreeCard").css('display','block');}
jQuery("#order_ticket").attr("class","order_ticket order_ticketBg");jQuery("#JustCouponPostfree").show();jQuery("#thepostfreeClose").hide();jQuery("#thepostfreeOpen").show();}
if(id=='onJustCouponfullcut')
{var virtualCardPriceForCheck=jQuery("#virtualCardPrice").html();if(jQuery("#CouponNumSwitch").val()>0){jQuery("#fullcutCard").html("<ul class='coupons'><li><span class='red'>温馨提示：满减券和羊展券不能同时使用</span></li></ul>");}else if(virtualCardPriceForCheck!=''&&virtualCardPriceForCheck!='0.00'){jQuery("#fullcutCard").html("<ul class='coupons'><li><span class='red'>温馨提示：满减券与GG券不能同时使用</span></li></ul>");}else{if(show2){var timetemp=(new Date()).valueOf();jQuery("#fullcutCard").load(frontPath+"/Card/fullcutCard.do?t="+timetemp);jQuery("#gouwuCard").css('display','none');}else
{jQuery("#fullcutCard").css('display','block');jQuery("#gouwuCard").css('display','none');}}
jQuery("#fullcutCard").css('display','block');jQuery("#order_ticket").attr("class","order_ticket order_ticketBg");jQuery("#JustCouponfullcut").show();jQuery("#thefullcutClose").hide();jQuery("#thefullcutOpen").show();}
if(id=='offJustCouponfullcut'){if(jQuery("#fullcutCard").css("display")=='none'){jQuery("#order_ticket").attr("class","order_ticket");}
jQuery("#JustCouponfullcut").hide();jQuery("#thefullcutClose").show();jQuery("#thefullcutOpen").hide();}
if(id=='offJustCoupon'){if(jQuery("#JustCard").css("display")=='none'){jQuery("#order_ticket").attr("class","order_ticket");}
jQuery("#JustCoupon").hide();jQuery("#theCouponClose").show();jQuery("#theCouponOpen").hide();}
if(id=='offJustCouponpostfree'){if(jQuery("#postfreeCard").css("display")=='none'){jQuery("#order_ticket").attr("class","order_ticket");}
jQuery("#JustCouponPostfree").hide();jQuery("#thepostfreeClose").show();jQuery("#thepostfreeOpen").hide();}
if(id=='onJustCard'){jQuery("#order_ticket").attr("class","order_ticket order_ticketBg");jQuery("#JustCard").show();jQuery("#theCardClose").hide();jQuery("#theCardOpen").show();}
if(id=='offJustCard'){if(jQuery("#JustCoupon").css("display")=='none'){jQuery("#order_ticket").attr("class","order_ticket");}
jQuery("#JustCard").hide();jQuery("#theCardClose").show();jQuery("#theCardOpen").hide();}
if(id=='onJustCouponNum'){var virtualCardPriceForCheck=jQuery("#virtualCardPrice").html();if(virtualCardPriceForCheck!=''&&virtualCardPriceForCheck!='0.00'){alert("温馨提示：GG券和羊展券不能同时使用");}else{jQuery("#gouwuCard").css('display','none');jQuery("#fullcutCard").css('display','none');jQuery("#CouponNumValue").val('');jQuery("#CouponNumSwitch").val('1');jQuery("#order_ticket").attr("class","order_ticket order_ticketBg");jQuery("#JustCouponNum").show();jQuery("#theCouponNumClose").hide();jQuery("#theCouponNumOpen").show();}}
if(id=='offJustCouponNum'){if(jQuery("#JustCoupon").css("display")=='none'){jQuery("#order_ticket").attr("class","order_ticket");}
jQuery("#CouponNumValue").val('');jQuery("#CouponNumSwitch").val('0');jQuery("#JustCouponNum").hide();jQuery("#theCouponNumClose").show();jQuery("#theCouponNumOpen").hide();var timetemp=(new Date()).valueOf();jQuery("#gouwuCard").load(frontPath+"/Card/gouWuCard.do?t="+timetemp);}}
function checkCouponsForm(){if(jQuery("#cardNum").val()==""){alert("请填写GG券编号");jQuery("#cardNum").focus();}else if(jQuery("#cardPassWord").val()==""){alert("请填写GG券密码");jQuery("#cardPassWord").focus();}else{jQuery("#cardNumReturn").val(jQuery("#cardNum").val());jQuery("#cardPasswordReturn").val(jQuery("#cardPassWord").val());jQuery("#insertForm").submit();}}
function checkCouponsForm2(){if(jQuery("#cardNum2").val()==""){alert("请填写免邮券编号");jQuery("#cardNum2").focus();}else if(jQuery("#cardPassWord2").val()==""){alert("请填写免邮券密码");jQuery("#cardPassWord2").focus();}else{jQuery("#cardNumReturn").val(jQuery("#cardNum2").val());jQuery("#cardPasswordReturn").val(jQuery("#cardPassWord2").val());jQuery("#insertForm").submit();}}
function checkCouponsForm3(){if(jQuery("#cardNum3").val()==""){alert("请填写满减券编号");jQuery("#cardNum3").focus();}else if(jQuery("#cardPassWord3").val()==""){alert("请填写满减券密码");jQuery("#cardPassWord3").focus();}else{jQuery("#cardNumReturn").val(jQuery("#cardNum3").val());jQuery("#cardPasswordReturn").val(jQuery("#cardPassWord3").val());jQuery("#insertForm").submit();}}
function resultIfm(){var msg=resultIfram.document.body.innerHTML;afertSubmit(msg);}
function afertSubmit(msg){var aData=msg.split(",");if(aData[0]=="0"){var timetemp=(new Date()).valueOf();jQuery("#gouwuCard").load(frontPath+"/Card/gouWuCard.do?t="+timetemp);alert("激活成功！");}
if(aData[0]=="1"){alert("激活不成功，请检查GG券编号或密码是否输入错误！");jQuery("#cardNum").val("");jQuery("#cardPassWord").val("");}}
function showCouponsNum(obj){if(obj.checked==true){jQuery("#coumponsNum").show();}else{jQuery("#coumponsNum").hide();}}
function showCouponsNum2(obj){if(obj.checked==true){jQuery("#coumponsNum2").show();}else{jQuery("#coumponsNum2").hide();}}
function showCouponsNum3(obj){if(obj.checked==true){jQuery("#coumponsNum3").show();}else{jQuery("#coumponsNum3").hide();}}
function saveInvoice(){getObj();}
function getObj(){var data=new userTradeInfo();data.userId=userid;var invoiceTitle2="";var showInvoice="(您的发票：";var personobj=document.getElementsByName("invoiceTitle");for(var j=0;j<personobj.length;j++){if(personobj[j].checked){invoiceTitle2=personobj[j].value;}}
if(invoiceTitle2==""){alert("请选择抬头类型！");return false;}
var personCompany=jQuery("#personName").val();personCompany=jQuery.trim(personCompany);if(personCompany==null||personCompany==""){alert("请填写发票抬头！");return false;}else{}
if(invoiceTitle2==1){showInvoice+="单位   ";}else if(invoiceTitle2==0){showInvoice+="个人   ";}
showInvoice+=personCompany;showInvoice+=" ";var perInvoiceContentElement=document.getElementById("perInvoiceContent1");var perInvoiceContent=perInvoiceContentElement.options[perInvoiceContentElement.selectedIndex].value;if("请选择"==perInvoiceContent){alert("请填写发票内容！");return false;}else{jQuery("#invoiceContent").val(perInvoiceContent);showInvoice+=perInvoiceContent;showInvoice+=")";}
jQuery("#theShowInvoiceId").show();jQuery("#theShowInvoiceId").html(showInvoice);jQuery("#companyName").val(personCompany);data.invoiceTitle=invoiceTitle2;data.regionId=0;data.deliveryModeId=0;data.companyName=personCompany;data.invoiceContent=perInvoiceContent;data.invoiceTitleType=0;var newEntrytoStr=JSON.stringify(data);jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});controlInvoiceDiv('off','orders_infom11');}
function showaperCompany(comId,showId){if(comId=="perInvoiceTitle1"&&jQuery("#"+comId).attr("checked")==true){jQuery("#personName").val("");}
if(comId=="perInvoiceTitle2"&&jQuery("#"+comId).attr("checked")==true){jQuery("#personName").val("");}}
function controlInvoiceDiv(isOn,id){if("on"==isOn){jQuery("#"+id).show();}else{jQuery("#"+id).hide();}}
function closeInvoiceDiv(id){jQuery("#"+id).hide();var personobj=document.getElementsByName("invoiceTitle");for(var j=0;j<personobj.length;j++){personobj[j].checked=false;}
jQuery("#personName").val("");jQuery("#theShowInvoiceId").hide();}
function closeIncludeOther(id){jQuery("#"+id).hide();jQuery("#remark").val("");jQuery("#theFJSMDiv").hide();}
String.prototype.replaceAll=function(s1,s2){return this.replace(new RegExp(s1,"gm"),s2);}
function savaOther(){getOther();}
function getOther(){if(jQuery("#remark").val()==null||jQuery("#remark").val()==''){alert("请填写附加信息！");return false;}
var newEntryto=new userTradeInfo();newEntryto.userId=userid;newEntryto.orderMemo=jQuery.trim(jQuery("#remark").val());newEntryto.regionId=0;newEntryto.deliveryModeId=0;var newEntrytoStr=JSON.stringify(newEntryto);jQuery.post(frontPath+"/Cart/saveUserTradeInfoFForjQuery.do?T="+Math.random(),{newEntrytoStr:newEntrytoStr});var theFJSm=document.getElementById("remark").value;jQuery("#theFJSM").html(theFJSm.replaceAll("\n","<BR/>"));controlInvoiceDiv('off','orders_infom4');controlInvoiceDiv('on','theFJSMDiv');}
function changePickupMode(id){jQuery("#pickupMode").val(id);var content="";if(id==1){content="先发有货商品,缺货商品不再发货";}else if(id==2){content="全部商品配齐才发货（时间会较久，不建议选择）";}else if(id==3){content="取消整张订单";}else if(id==4){content="有缺货电话通知（会延误配送时间，慎选）";}
jQuery("#showPickupMode").html(content);}
function initTelTip(){jQuery("#heckout_consignee_input4").html("例如：020-12345678-5587");}
function showRuduceValue(){if(jQuery("#ifReduceCheckBox").attr("checked")==true){var virtualCardPriceForCheck=jQuery("#virtualCardPrice").html();if(virtualCardPriceForCheck!=''&&virtualCardPriceForCheck!='0.00'){alert("温馨提示：GG券和订单减免不能同时使用");jQuery("#ifReduceCheckBox").attr("checked",false);jQuery("#orderReduceSwitch").val('0');}else if(jQuery("#CouponNumSwitch").val()>0){alert("温馨提示：羊展券和订单减免不能同时使用");jQuery("#ifReduceCheckBox").attr("checked",false);jQuery("#orderReduceSwitch").val('0');}else{jQuery("#gouwuCard").empty();jQuery("#gouwuCard").html("<ul class='coupons'><li><span class='red'>温馨提示：GG券和订单减免不能同时使用</span></li></ul>");var allprice=jQuery("#shoppingcarttotalprice1").html();var reducePirce=jQuery("#ifReduceCheckBox").val();var allprice2=parseFloat(allprice)- parseFloat(reducePirce);if(allprice2<0){alert("温馨提示，您的支付金额大于订单需要金额，请检查，谢谢");jQuery("#ifReduceCheckBox").attr("checked",false);jQuery("#orderReducePrice").html("0.00");jQuery("#shoppingcarttotalprice1").html(allprice);jQuery("#orderReduceSwitch").val('0');}else{jQuery("#orderReducePrice").html(reducePirce);jQuery("#shoppingcarttotalprice1").html(allprice2.toFixed(2));jQuery("#orderReduceSwitch").val('1');}}}else{var timetemp=(new Date()).valueOf();jQuery("#gouwuCard").load(frontPath+"/Card/gouWuCard.do?t="+timetemp);var allprice=jQuery("#shoppingcarttotalprice1").html();var reducePirce=jQuery("#ifReduceCheckBox").val();var allprice2=parseFloat(allprice)+ parseFloat(reducePirce);jQuery("#orderReducePrice").html("0.00");jQuery("#shoppingcarttotalprice1").html(allprice2.toFixed(2));jQuery("#orderReduceSwitch").val('0');}}
function checkCouponNum(){var num=jQuery("#CouponNumValue").val();var virtualCardPriceForCheck=jQuery("#virtualCardPrice").html();if(virtualCardPriceForCheck!=''&&virtualCardPriceForCheck!='0.00'){alert("温馨提示：GG券和羊展券不能同时使用");jQuery("#CouponNumValue").val('');onchangeCardAndCoupon('offJustCouponNum');jQuery("#CouponNumSwitch").val('0');return false;}else if(jQuery("#ifReduceCheckBox").attr("checked")==true){alert("温馨提示：订单满减和羊展券不能同时使用");jQuery("#CouponNumValue").val('');onchangeCardAndCoupon('offJustCouponNum');jQuery("#CouponNumSwitch").val('0');return false;}else if(jQuery("#CouponNumSwitch").val()>0){var tot=(jQuery("#cartTotalPrice").html()*100).toFixed(0);jQuery.post(frontPath+"/orderReduct/checkCouponNum.do",{num_:num,tot_:tot},function(json){var data=eval('('+ json+')');if(data.result==true){jQuery("#couponNumMsg").attr("class","reginfo_trcheck").html("羊展券号正确");var allprice=jQuery("#shoppingcarttotalprice1").html();var reducePirce=data.reduceValue/100;var reducePirceOrg=jQuery("#orderReduceNumPrice").html();var allprice2=parseFloat(allprice)- parseFloat(reducePirce)+ parseFloat(reducePirceOrg);if(allprice2<0){alert("温馨提示，您的支付金额大于订单需要金额，请检查，谢谢");jQuery("#CouponNumSwitch").val('1');jQuery("#orderReduceNumPrice").html("0.00");jQuery("#shoppingcarttotalprice1").html(allprice);}else{jQuery("#CouponNumReduceValue").val(data.reduceValue);jQuery("#orderReduceNumPrice").html(reducePirce.toFixed(2));jQuery("#shoppingcarttotalprice1").html(allprice2.toFixed(2));jQuery("#CouponNumSwitch").val('2');}
return true;}else{jQuery("#couponNumMsg").attr("class","reginfo_wrong").html("羊展券号错误");jQuery("#CouponNumSwitch").val('1');var allprice=jQuery("#shoppingcarttotalprice1").html();var reducePirce=jQuery("#orderReduceNumPrice").html();var allprice2=parseFloat(allprice)+ parseFloat(reducePirce);jQuery("#orderReduceNumPrice").html("0.00");jQuery("#shoppingcarttotalprice1").html(allprice2.toFixed(2));return false;}});}}