var SelectTree=new Object();jQuery.extend(SelectTree,{ShowChildren:function(selElem,initValue){var curNodeId=jQuery(selElem).val();var theValueElem=jQuery(selElem).attr("valueElemId");var treeBean=jQuery("#"+ theValueElem).attr("treeBean");var extraParam=jQuery("#"+ theValueElem).attr("extraParam");var level=jQuery(selElem).attr("level");jQuery("#"+ theValueElem).val(curNodeId);SelectTree.removeSubSelects(theValueElem,level);if(!curNodeId){return;}
var fn;if(!initValue){fn=new Function("nodes","SelectTree.addChildren(nodes,'"+ theValueElem+"',"+ level+")");}else{fn=new Function("nodes","SelectTree.addChildren(nodes,'"+ theValueElem+"',"+ level+","+ initValue+")");}
if(!isNaN(curNodeId)){if(!extraParam){extraParam=null;}
jQuery.post(frontPath+"/Cart/getChildrenForjQuery.do?T="+ Math.random(),{treeBean:treeBean,curNodeId:curNodeId,extraParam:extraParam},fn);}},removeSubSelects:function(valueElemId,level){var hasRemove=false;var treeName=jQuery("#"+ valueElemId).attr("treeName");var curLevel=Number(level)+ 1;for(var i=curLevel;i<10;i++){var elemId=treeName+"_"+ i;if(!jQuery("#"+ elemId)){break;}
jQuery("#"+ elemId).remove();hasRemove=true;}
if(hasRemove){var handler=jQuery("#"+ valueElemId).attr("onChangeHandler");if(handler){var fn1=new Function("id",handler);fn1("");}}},addChildren:function(node,valueElemId,level,initValue){node=jQuery.trim(node);var nodes=eval(node);var treeName=jQuery("#"+ valueElemId).attr("treeName");var parentId=treeName+"_"+ level;var curLevel=level+ 1;for(var i=level+ 1;i<10;i++){var elemId=treeName+"_"+ i;if(!jQuery("#"+ elemId)){break;}
jQuery("#"+ elemId).remove();}
if(nodes.length==0){var effectiveNodes=jQuery("#"+ valueElemId).attr("nodePath","");var handler=jQuery("#"+ valueElemId).attr("onChangeHandler");if(handler){var fn1=new Function("id",handler);fn1(jQuery("#"+ valueElemId).val());}
return 0;}
var html="<select class='selectTree' id='"+ treeName+"_"+ curLevel+"' onchange='SelectTree.ShowChildren(this)'";html+=" valueElemId='"+ valueElemId+"' level='"+ curLevel+"'>";html+="<option>«Î—°‘Ò...</option>";for(var i=0;i<nodes.length;i++){html+="<option value='"+ nodes[i].ID+"'>"+ nodes[i].name+"</option>";}
html+="</select>";jQuery("#"+ treeName+"Canvas").append(html);var sNodePath=jQuery("#"+ valueElemId).attr("nodePath");if(sNodePath&&sNodePath.length&&sNodePath.length>0){var effectiveNodes=sNodePath.split(",");var currentID=effectiveNodes[curLevel];if(currentID){jQuery("#"+treeName+"_"+ curLevel).val(currentID);SelectTree.ShowChildren("#"+ treeName+"_"+ curLevel);}}
if(initValue){SelectTree.setValue(valueElemId,initValue);}},show:function(valueElem){var cla=jQuery(valueElem).attr("class");if(cla!="selectTree"){return;}
var treeName=jQuery(valueElem).attr("treeName");var initValue=jQuery(valueElem).val();var parentId=treeName+"_"+ 0;SelectTree.ShowChildren(jQuery("#"+ parentId),initValue);},init:function(){jQuery(".selectTree").each(function(i){SelectTree.show(this);});},showTreePath:function(node,elemId){node=jQuery.trim(node);var nodes=eval(node);var treeName=jQuery("#"+ elemId).attr("treeName");var topColumnId=jQuery("#"+ treeName+"_0").val();var sNodePath="";var first=true;var beginAddPath=false;for(var i=nodes.length- 1;i>=0;i--){if(nodes[i].ID==topColumnId){beginAddPath=true;}
if(beginAddPath){if(first){sNodePath=nodes[i].ID;first=false;}
else{sNodePath+=","+ nodes[i].ID;}}}
jQuery("#"+ elemId).attr("nodePath",sNodePath);SelectTree.ShowChildren(jQuery("#"+ treeName+"_0"));},setValue:function(elemId,value){var treeName=jQuery("#"+ elemId).attr("treeName");for(var i=1;i<10;i++){var temId=treeName+"_"+ i;if(!jQuery("#"+ temId)){break;}
jQuery("#"+ temId).remove();}
jQuery("#"+ elemId).val(value);var treeBean=jQuery("#"+ elemId).attr("treeBean");var fn=new Function("nodes","SelectTree.showTreePath(nodes,'"+ elemId+"')");jQuery.post(frontPath+"/Cart/getNodePathForjQuery.do?T="+ Math.random(),{treeBean:treeBean,value:value},fn);},clear:function(elemId){var treeName=jQuery("#"+ elemId).attr("treeName");jQuery("#"+ elemId).val("");SelectTree.ShowChildren(jQuery("#"+ treeName+"_0"));}});jQuery(SelectTree.init);